language: php
group: legacy
php:
- 5.6
- 5.3.3
services:
- redis-server
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python2.6
    - python2.6-dev
    - nginx
    - realpath
    - lftp
env:
  global:
  - PLUGIN_NAME=AdvancedCampaignReporting
  - PIWIK_ROOT_DIR=$TRAVIS_BUILD_DIR/piwik
  - UNPROTECTED_ARTIFACTS=1
  - PIWIK_REPOSITORY_SLUG=PiwikPRO/piwik.git
  - PIWIK_LATEST_STABLE_TEST_TARGET=master
  - secure: "fEnu9C+KbqECUB8IUxq5dSMV/XkrU1eusSfeG1tQC1Fow+hBjbDdlclonf2pwfh8CJtvhs1IMRdaAIwEyRHbny8SK+wrg+vzQXoY93UN0na3siTY91MdpgIlSKbNaLHxIXKptK8SWr5oGv2hQIlYD6WXhUZhsFSlSg12qK7W/rHn9G5e/q4Tk2kI1qEdvISHDZLYWkgQg3T0aXwGyL5IJu/r8GU1rB5fsQo2XB5sjAoafkLnuORAGGKrtEfGmideSQOmp++/a4DBS9kFTRrY7yNEgTW/bollz7bQ7ZSZkg5Phfym9bx1O+TFTriuMIOXZd+fo/fs16TEDEZgsrLOznAv7/E7Ej/WyhwT9zGD6CDnVCHEFzLbtUiToeBEDflfk8ydWYnPsSCyVOMmfX0HMPxAg4JKDdH0dOke9GuwrY0EN/SOvuIdihs/jZyDhsz2e1IaAOmvVoUd3L0Y+m7sI8NW+tsYh63MN0xDufzzxHn+i9fHplakSUKidhlC8hE/i8hYzOOfQmV4MnX5vrbSRokAGm+e5f7yz2eoeNRUYH9YKGgo8spC7Y75MXxXJZqm2KWv71SB5D30KcvHmIbPjTmoj/ITM5Jk/bhJh4WLAYRZceZjNJL7Bjlq07ajlvHOHB6m00zGQ6UpS7U9uxteMkP1tVO8Rrj8BNJsfSjH1/0="
  - secure: "yoSGUVYP9zOx42ZfwizIyzJPwnp6UczS9vmufje85SF5HL5ojHWqWUnhWly1Ml8oSCDO9/QhkHGiwjrnYHhlYmPKWTOVn6mcLWUcR81ogPCdPVK5EogOHslWV4H1ZyksnxktZr9/hbf79dNdcpiWv+vwQsQgoElkFpaTOIzC5FRmqj4eoKqdjA5eEupcbxynYO43eKn9GRHZPZJUL3lUUmiW0QUus8HASAfGwQRnhVHxZ115ei67FEM3v/cVy3iyGYNI+Y/mK7OhtQc93CvgEgWaU0HYhdstvnWeNPYdHz4ohNfP3dj3WQYuWuixbeM9douoJEQ64871rW4vEdL304nTArLgJXCaLBOiK45K1Hw7JrsEIlEx7JnR1LxMJ/HOKLgdow/jvEVjgIX0bX+dWMNV8oRSxCS+DWZeztjtjgAHHtZqlRRngEt6wajU2BJZhUcEDI4DbXlCm+e9LmhTGP2oN4P7dNvvo/w0kl2/njGQhTZ5o/xt2s//aR1JpuFodx/qCBaljfeGIZWaNchzgcw/+GEUqingtFyGVDkDoe2RY3fJgyaYUrdWCMACcOwT+1JsNJnpaEH+wDiv6Sn8656CBEykJ/pVn8g9GfD3pMBawP4e3W32QFd9mK9ZLB80oATbF8CAENEqcgcZdHrjvdjoWrtCRT0PT0FyOvoEKi4="
  matrix:
  - TEST_SUITE=PluginTests MYSQL_ADAPTER=PDO_MYSQL TEST_AGAINST_PIWIK_BRANCH=3.x-pro
  - TEST_SUITE=UITests MYSQL_ADAPTER=PDO_MYSQL TEST_AGAINST_PIWIK_BRANCH=3.x-pro
matrix:
  exclude:
  - php: 5.3.3
sudo: required
script: "$PIWIK_ROOT_DIR/tests/travis/travis.sh"
before_install:
- '[[ "$TRAVIS_PHP_VERSION" == 5.3* ]] && export USE_ZEND_ALLOC=0 || true'
- wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
- tar -xjf phantomjs-2.1.1-linux-x86_64.tar.bz2
- sudo rm -rf /usr/local/phantomjs/bin/phantomjs
- sudo mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/phantomjs/bin/phantomjs
install:
- mkdir $PLUGIN_NAME
- cp -R !($PLUGIN_NAME) $PLUGIN_NAME
- cp -R .git/ $PLUGIN_NAME/
- cp .travis.yml $PLUGIN_NAME
- git clone -q https://$GITHUB_USER_TOKEN:@github.com/$PIWIK_REPOSITORY_SLUG piwik
- cd piwik
- git fetch -q --all
- git submodule update
- '[ -d ./tests/travis/.git ] || sh -c "rm -rf ./tests/travis && git clone https://$GITHUB_USER_TOKEN:@github.com/PiwikPRO/travis-scripts.git ./tests/travis"'
- cd ./tests/travis ; git checkout master ; cd ../..
- "./tests/travis/checkout_test_against_branch.sh"
- '[ "$PLUGIN_NAME" == "" ] || [ ! -f ./tests/travis/check_plugin_compatible_with_piwik.php ] || php ./tests/travis/check_plugin_compatible_with_piwik.php "$PLUGIN_NAME"'
- "./tests/travis/configure_git.sh"
- '[ "$SKIP_COMPOSER_INSTALL" == "1" ] || travis_retry composer install'
- rm -rf plugins/$PLUGIN_NAME
- mv ../$PLUGIN_NAME plugins
- "./tests/travis/checkout_dependent_plugins.sh"
before_script:
- if [[ "$TRAVIS_PHP_VERSION" != 7* ]]; then phpenv config-rm xdebug.ini; fi
- echo "always_populate_raw_post_data=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "opcache.enable=0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- mysql --version
- mysql -e "SELECT VERSION();"
- mysql -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES'"
- mysql -e "SET GLOBAL wait_timeout = 36000;"
- mysql -e "SET GLOBAL max_allowed_packet = 134209536;"
- mysql -e "SHOW VARIABLES LIKE 'max_allowed_packet';"
- mysql -e "SHOW VARIABLES LIKE 'wait_timeout';"
- mysql -e "SELECT @@sql_mode;"
- uname -a
- date
- php -r "var_dump(gd_info());"
- mysql -e 'create database piwik_tests;'
- "./tests/travis/prepare.sh"
- "./tests/travis/setup_webserver.sh"
- cd tests/PHPUnit
after_script:
- cd $PIWIK_ROOT_DIR
- cat $PIWIK_ROOT_DIR/tests/travis/error.log
- cat $PIWIK_ROOT_DIR/tmp/php-fpm.log
- cat $PIWIK_ROOT_DIR/tmp/logs/piwik.log
- cat $PIWIK_ROOT_DIR/config/config.ini.php
- "./tests/travis/upload_artifacts.sh"
after_success:
- cd $PIWIK_ROOT_DIR
